### ISSUE TITLE
Foreman fails to start after Update to Version 2.0.x

### ISSUE THREAD

**Issue by mgast-mpifr** [ATIX-AG/foreman_snapshot_management#86] opened 2023-07-11 13:57 UTC
After i installed a Version 2.0.x of this Module i get 

> 2023-07-11T15:51:18 [I|app|2f69a395] Completed 500 Internal Server Error in 161ms (ActiveRecord: 21.4ms | Allocations: 53828)     
> 2023-07-11T15:51:18 [F|app|2f69a395]                                                                                              
> 2f69a395 | ActionView::Template::Error (Can't find entry point 'foreman_snapshot_management:global' in webpack manifest):        
> 2f69a395 |     13:     <%= stylesheet_link_tag *webpack_asset_paths('foreman-vendor', :extension => 'css') %>                    
> 2f69a395 |     14:     <%= stylesheet_link_tag *webpack_asset_paths('bundle', :extension => 'css') %>                            
> 2f69a395 |     15:     <%= stylesheet_link_tag 'application' %>                                                                  
> 2f69a395 |     16:     <%= webpacked_plugins_with_global_css %>                                                                 
> 2f69a395 |     17:     <%= yield(:stylesheets) %>                                                                                
> 2f69a395 |     18:                                                                                                               
> 2f69a395 |     19:     <%= csrf_meta_tags %> 

Foreman Version 3.4.1
Ruby Version: 2.7.0
OS: Debian 11

**Comment by nadjaheitmann** [comment] 2023-07-13 08:28
@mgast-mpifr What exactly were the steps you followed to install the plugin?

**Comment by mgast-mpifr** [comment] 2023-07-13 14:53
@nadjaheitmann first changed the Version Tag in /usr/share/foreman/bundler.d/Gemfile.local.rb to 2.0.3.
Next i ran  `/usr/bin/foreman-ruby /usr/bin/bundle update` while being in the Folder /usr/share/foreman as root.
Then i made run of ` foreman-installer`.
Finally i made a restart of the foreman service.

**Comment by nadjaheitmann** [comment] 2023-07-14 08:17
I think the problem is that this plugin uses webpack from version > 2 and webpack needs to be precompiled in order to work. Afaik, you need specific tooling for that which is not installed on Foreman by default. If you want the plugin to work as before, you need to go back to the latest 1.x version.

I will try to make the new package available for Debian systems such that you can install it via apt. I'll keep you posted.

**Comment by nadjaheitmann** [comment] 2023-07-14 11:10
I have opened a PR in foreman-packaging: https://github.com/theforeman/foreman-packaging/pull/9576

**Comment by nadjaheitmann** [comment] 2023-08-24 08:00
Finally merged!

**Closed** 2023-08-25 08:49 UTC
